SET IDENTITY_INSERT [dbo].[Products] ON
INSERT INTO [dbo].[Products] ([Id], [Name], [Description]) VALUES (NULL, "RSSO1A", "A Locus")
INSERT INTO [dbo].[Products] ([Id], [Name], [Description]) VALUES (NULL, "RSSO1B", "B Locus")
INSERT INTO [dbo].[Products] ([Id], [Name], [Description]) VALUES (NULL, "RSSO1C", "C Locus")
INSERT INTO [dbo].[Products] ([Id], [Name], [Description]) VALUES (NULL, "RSSO1CT", "C Locus")
INSERT INTO [dbo].[Products] ([Id], [Name], [Description]) VALUES (NULL, "RSSO1E47", "Exon 4-7")
INSERT INTO [dbo].[Products] ([Id], [Name], [Description]) VALUES (NULL, "RSSO1S1", "B7")
INSERT INTO [dbo].[Products] ([Id], [Name], [Description]) VALUES (NULL, "RSSO1S4", "Bw4")
INSERT INTO [dbo].[Products] ([Id], [Name], [Description]) VALUES (NULL, "RSSO2345", "DRB3,4,5")
INSERT INTO [dbo].[Products] ([Id], [Name], [Description]) VALUES (NULL, "RSSO2B1", "DRB1")
INSERT INTO [dbo].[Products] ([Id], [Name], [Description]) VALUES (NULL, "RSSO2P", "DPA1/DPB1")
INSERT INTO [dbo].[Products] ([Id], [Name], [Description]) VALUES (NULL, "RSSO2Q", "DQA1/DQB1")
INSERT INTO [dbo].[Products] ([Id], [Name], [Description]) VALUES (NULL, "RSSOH1A", "HD A Locus")
INSERT INTO [dbo].[Products] ([Id], [Name], [Description]) VALUES (NULL, "RSSOH1B", "HD B Locus")
INSERT INTO [dbo].[Products] ([Id], [Name], [Description]) VALUES (NULL, "RSSOH1C", "HD C Locus")
INSERT INTO [dbo].[Products] ([Id], [Name], [Description]) VALUES (NULL, "RSSOH2B1", "HD DRB1")
SET IDENTITY_INSERT [dbo].[Products] OFF
